apiVersion: v1
kind: Namespace
metadata:
  name: moomoo-platform
  labels:
    name: moomoo-platform
    app: moomoo-trading-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: moomoo-users
  labels:
    name: moomoo-users
    app: moomoo-trading-platform